# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'reek', '~> 6.3'
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-rspec', '~> 2.26'
  gem 'simplecov', '~> 0.22'
end
