name: Verify Bowling(ruby) 
on:
  push:
    paths:
    - 'bowling/ruby/**'
jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bowling/ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Bundle
        run: bundle install
      - name: RSpec
        id: rspec
        run: | 
          bundle exec rspec
          echo "coverage=$(jq '.result.line' ./coverage/.last_run.json)" >> "$GITHUB_OUTPUT"
      - name: Coverage
        uses: actions/github-script@v7
        env:
          COVERAGE: ${{steps.rspec.outputs.coverage}}
        with:
          script: |
            const lineCoverage = parseFloat(process.env.COVERAGE);

            if (isNaN(lineCoverage)) {
              core.setFailed('Invalid coverage value');
            } else if (lineCoverage === 100) {
              core.info('Perfect! Code coverage is 100%. This Is The Way!');
            } else if (lineCoverage < 90) {
              core.setFailed(`Code coverage ${lineCoverage}% (less than 90%) is not acceptable`);
            } else {
              core.info(`Code coverage ${lineCoverage}% (more than 90%) is satisfactory, but not perfect.`);
            }        
        if: ${{ !cancelled() }}        
      - name: Reek
        run: bundle exec reek ./** -c ./.reek.yml -V
        if: ${{ !cancelled() }}
      - name: Rubocop
        run: bundle exec rubocop
        if: ${{ !cancelled() }}