name: Verify Bowling(ruby) 
on:
  push:
    paths:
    - 'bowling/ruby/**'
jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bowling/ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Bundle
        run: bundle install
      - name: RSpec
        run: | 
          bundle exec rspec
          echo "coverage=$(jq '.result.line' ./coverage/.last_run.json)" >> "$GITHUB_OUTPUT"
      - name: Coverage
        uses: actions/github-script@v7
          with:
            script: |
              console.log(context)
              console.log(steps)
        if: ${{ !cancelled() }}        
      - name: Reek
        run: bundle exec reek ./** -c ./.reek.yml -V
        if: ${{ !cancelled() }}
      - name: Rubocop
        run: bundle exec rubocop
        if: ${{ !cancelled() }}