name: Test
on: 
  push:
    paths:
      - './bowling/ruby/**'
  pull_request:
    paths:
      - './bowling/ruby/**'  
jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bowling/ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec
      
    
